/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rb_codec_rb_codec */

#ifndef _Included_com_rb_codec_rb_codec
#define _Included_com_rb_codec_rb_codec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rb_codec_rb_codec
 * Method:    InitEncode
 * Signature: (ZIIIIIIIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rb_1codec_rb_1codec_InitEncode
  (JNIEnv *, jobject, jboolean, jint, jint, jint, jint, jint, jint, jint, jint, jstring,jint);

/*
 * Class:     com_rb_codec_rb_codec
 * Method:    UnInitEncode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rb_1codec_rb_1codec_UnInitEncode
  (JNIEnv *, jobject);

/*
 * Class:     com_rb_codec_rb_codec
 * Method:    EncodeYUVToRTP
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_rb_1codec_rb_1codec_EncodeYUVToRTP
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_rb_codec_rb_codec
 * Method:    EncodePCMToRTP
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_rb_1codec_rb_1codec_EncodePCMToRTP
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
